language: node_js
node_js:
  - "4"

before_install:
  - npm install bower -g
  - npm install grunt-cli -g
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start
  
script:
  - grunt karma:singleRun
  - ./node_modules/.bin/protractor protractor.conf.js
 
after_success: 'npm run coveralls'

branches:
  only:
    - master
    - CI_FIX
  
cache:
  directories:
  - www/bower_components
  - node_modules

notifications:
  email: true